// src/utils/permissions.js
export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_PRODUCTS: 'view_products',
  ADD_PRODUCT: 'add_product',
  EDIT_PRODUCT: 'edit_product',
  DELETE_PRODUCT: 'delete_product',
  BULK_DISCOUNT: 'bulk_discount',
  MANAGE_BRANDS: 'manage_brands',
  MANAGE_TAGS: 'manage_tags',
  MANAGE_PARTNERS: 'manage_partners',
  IMPORT_EXPORT: 'import_export',
  EDIT_SALES_MODE: 'edit_sales_mode',
  EDIT_LANDING_TAGS: 'edit_landing_tags',
  RESET_DATA: 'reset_data',
  MANAGE_EMPLOYEES: 'manage_employees',
  CREATE_QUOTE: 'create_quote',
  VIEW_QUOTES: 'view_quotes',
  MANAGE_QUOTES: 'manage_quotes',
};

export const PERMISSIONS_LIST = [
  { key: PERMISSIONS.VIEW_DASHBOARD, label: 'مشاهده داشبورد' },
  { key: PERMISSIONS.VIEW_PRODUCTS, label: 'مشاهده محصولات' },
  { key: PERMISSIONS.ADD_PRODUCT, label: 'افزودن محصول جدید' },
  { key: PERMISSIONS.EDIT_PRODUCT, label: 'ویرایش محصول' },
  { key: PERMISSIONS.DELETE_PRODUCT, label: 'حذف محصول' },
  { key: PERMISSIONS.BULK_DISCOUNT, label: 'تخفیف گروهی' },
  { key: PERMISSIONS.MANAGE_BRANDS, label: 'مدیریت برندها' },
  { key: PERMISSIONS.MANAGE_TAGS, label: 'مدیریت تگ‌ها' },
  { key: PERMISSIONS.MANAGE_PARTNERS, label: 'مدیریت همکاران' },
  { key: PERMISSIONS.IMPORT_EXPORT, label: 'ورود و خروج داده' },
  { key: PERMISSIONS.EDIT_SALES_MODE, label: 'تغییر روش فروش' },
  { key: PERMISSIONS.EDIT_LANDING_TAGS, label: 'انتخاب تگ‌های صفحه اصلی' },
  { key: PERMISSIONS.RESET_DATA, label: 'بازنشانی داده‌ها' },
  { key: PERMISSIONS.MANAGE_EMPLOYEES, label: 'مدیریت کارمندان' },
  { key: PERMISSIONS.CREATE_QUOTE, label: 'ایجاد پیش‌فاکتور' },
  { key: PERMISSIONS.VIEW_QUOTES, label: 'مشاهده پیش‌فاکتورها' },
  { key: PERMISSIONS.MANAGE_QUOTES, label: 'مدیریت پیش‌فاکتورها' },
];